import "@css";

import { Metadata } from "next";
import { Inter } from "next/font/google";
import { dir } from "i18next";
import { languages } from "@i18n/settings";
import { RootLayoutProps } from "@types";

const inter = Inter({ subsets: ["latin"] });

/**
 * Statically generate dynamic routes by providing key:value pairs
 * Keys relate to the dynamic routes => [lang]
 * Values relate to the pathname => en
 */
export async function generateStaticParams() {
  // returns [{lang: en}, {lang: de}]
  return languages.map((lang) => ({
    lang,
  }));
}

export const metadata: Metadata = {
  title: "HarmonyScape",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: RootLayoutProps) {
  return (
    // dir from i18next takes a language and returns the direction of the language
    <html lang={lang} dir={dir(lang)}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
